[package]
name = "fibonacii-heap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8"
criterion = "0.3"

[[bench]]
name = "time_complexity"
harness = false
